### ISSUE TITLE
Menu not loading and Not Secure Warning

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/tat-addin#13]
@MattReimer this is a low priority thing... I was trying to go to all our sites that had not had the topmenu updated and replace it with:
```yml
  topmenu:
    - title: "Riverscapes Consortium"
      url: http://riverscapes.xyz
    - title: "Tools"
      url: https://riverscapes.xyz/Tools/
    - title: "Data"
      url: https://data.riverscapes.xyz
    - title: "Maps"
      url: https://maps.riverscapes.xyz
```
After making [this commit](https://github.com/Riverscapes/tat-addin/commit/dea837760ba7b204be6e2cc003a3d0197f0993ed) the menu went away... Am I doing something wrong?

![image](https://user-images.githubusercontent.com/9723905/130335044-586f4714-25df-46c1-b5d0-3e1ccab3f705.png)

Probably unrelated, but any idea why the site shows up as "insecure"?
